pipeline {
    
    agent any
    
    tools {
        nodejs('NodeJS-15.6.0')
    }
    
    stages {
        stage('Build') {
            steps {
                    sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'ng serve --open'
            }
        }

    }
}
