pipeline {
    
    agent any
    
    tools {
        nodejs('NodeJS-15.6.0')
    }
    
    stages {
        stage('Build') {
            steps {
                    sh 'ls -al'
                    sh 'npm install'
                    sh 'npm install -g @angular/cli'
            }
        }
        stage('Test') {
            steps {
              
              sh 'cd restaurantapp | ls -al | ng serve'
              
                sh 'ls -al'
                          }
        }

    }
}
